"""initial schema

Revision ID: 2ac09b62c78a
Revises: 
Create Date: 2026-07-04 09:24:49.783870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac09b62c78a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('alert_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DOWN', 'PAUSED', name='monitorstatus', native_enum=False, length=20), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitors_device_id'), 'monitors', ['device_id'], unique=True)
    op.create_table('monitor_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('MONITOR_CREATED', 'HEARTBEAT_RECEIVED', 'ALERT_TRIGGERED', 'PAUSED', 'RESUMED', name='eventtype', native_enum=False, length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_events_monitor_id'), 'monitor_events', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_events_monitor_id'), table_name='monitor_events')
    op.drop_table('monitor_events')
    op.drop_index(op.f('ix_monitors_device_id'), table_name='monitors')
    op.drop_table('monitors')
    # ### end Alembic commands ###
