"""add deleted_at for retention-based purge

Revision ID: b6709bf03daf
Revises: 2ac09b62c78a
Create Date: 2026-07-04 14:04:33.712699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6709bf03daf'
down_revision: Union[str, None] = '2ac09b62c78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('monitors', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'deleted_at')
    op.drop_column('monitors', 'is_deleted')
    # ### end Alembic commands ###
